#!/usr/bin/env python3
"""Sinh macro cho ket qua lap NHIEU KY NGUYEN TLE. So headline phai co MOT CHO O.

⛔ Bai nay truoc day go tay moi con so cua Bang III vao .tex. Lan nay khong lam the:
moi con so di vao ban thao deu sinh tu results/bang3_nhieu_ky_nguyen_*.csv.

⛔ TY SO phai tinh tren TONG, khong phai trung binh cua tung ty so. Mot ky nguyen co
mau so 0 se lam ty so vo han va keo trung binh thanh vo nghia; day dung la cho bai da
tung viet "∞" vao bang.

    python3 scripts/emit_macro_nhieu_ky_nguyen.py
    python3 scripts/emit_macro_nhieu_ky_nguyen.py --tu-kiem
"""
import argparse
import csv
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RES = os.path.join(ROOT, "results")
OUT = os.path.join(RES, "tables", "r2_nhieu_ky_nguyen.tex")

# (che do, tien to macro, so cua Bang III da cong bo de DOI CHIEU dong dau tien)
CHE_DO = [("long", "Long", (5, 18)), ("sparse", "Sparse", (0, 2))]


def doc(che_do):
    p = os.path.join(RES, "bang3_nhieu_ky_nguyen_%s.csv" % che_do)
    if not os.path.exists(p):
        return None
    return list(csv.DictReader(io.open(p, encoding="utf-8")))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tu-kiem", action="store_true")
    if ap.parse_args().tu_kiem:
        return tu_kiem()

    L = [r"% Auto-generated by scripts/emit_macro_nhieu_ky_nguyen.py -- KHONG sua tay"]
    thieu = []
    for che_do, tien_to, neo in CHE_DO:
        r = doc(che_do)
        if not r:
            thieu.append(che_do)
            continue
        s = [int(x["sec_static"]) for x in r]
        a = [int(x["sec_adapt"]) for x in r]

        # ⛔ DOI CHIEU: ky nguyen DAU TIEN phai tra ve dung con so cua Bang III da
        # cong bo. Neu khong thi bo do moi va bai dang do HAI thu khac nhau, va moi
        # con so duoi day deu vo nghia. Dung o day chu khong ghi ra.
        if (s[0], a[0]) != neo:
            sys.exit("⛔ che do %s: ky nguyen dau tien cho (%d, %d) nhung Bang III da "
                     "cong bo (%d, %d). Bo do moi KHONG tai lap duoc bai. Dung lai."
                     % (che_do, s[0], a[0], neo[0], neo[1]))

        L += [r"\newcommand{\r%sEpochs}{%d}" % (tien_to, len(r)),
              r"\newcommand{\r%sStatMean}{%.1f}" % (tien_to, sum(s) / len(s)),
              r"\newcommand{\r%sStatLo}{%d}" % (tien_to, min(s)),
              r"\newcommand{\r%sStatHi}{%d}" % (tien_to, max(s)),
              r"\newcommand{\r%sAdaptMean}{%.1f}" % (tien_to, sum(a) / len(a)),
              r"\newcommand{\r%sAdaptLo}{%d}" % (tien_to, min(a)),
              r"\newcommand{\r%sAdaptHi}{%d}" % (tien_to, max(a)),
              r"\newcommand{\r%sStatZero}{%d}" % (tien_to, sum(1 for x in s if x == 0)),
              r"\newcommand{\r%sStatTot}{%d}" % (tien_to, sum(s)),
              r"\newcommand{\r%sAdaptTot}{%d}" % (tien_to, sum(a))]
        if sum(s) > 0:
            L.append(r"\newcommand{\r%sRatio}{%.1f}" % (tien_to, sum(a) / sum(s)))
        else:
            # Khong sinh macro ty so. Cau van trong bai phai viet bang DEM, nhu muc
            # sparse cua ban cu. De macro ton tai se moi nguoi viet mot ty so vo nghia.
            print("  chu y: che do %s co TONG tinh = 0, KHONG sinh macro ty so" % che_do)

    if thieu:
        print("  chu y: chua co du lieu cho %s" % ", ".join(thieu))
    if len(L) == 1:
        sys.exit("⛔ khong co du lieu nao, khong ghi gi ca")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    io.open(OUT, "w", encoding="utf-8").write("\n".join(L) + "\n")
    print("ghi %s (%d macro)" % (os.path.relpath(OUT, ROOT), len(L) - 1))
    for x in L[1:]:
        print("   " + x)
    return 0


def tu_kiem():
    """Doi chung: cong doi chieu ky nguyen dau tien co that su chan khong."""
    import tempfile, subprocess
    print("== TU KIEM bo sinh macro ==\n")
    ok = True
    d = tempfile.mkdtemp()
    os.makedirs(os.path.join(d, "results", "tables"), exist_ok=True)
    # du lieu BIA, ky nguyen dau tien KHONG khop Bang III
    p = os.path.join(d, "results", "bang3_nhieu_ky_nguyen_long.csv")
    io.open(p, "w").write("che_do,tram,ky_nguyen,sec_static,sec_adapt,cap_tong,buoc_phuc_vu\n"
                          "long,X,2026-05-23,99,99,201,67\n")
    r = subprocess.run([sys.executable, __file__], capture_output=True, text=True,
                       env=dict(os.environ))
    # chay voi RES tro vao thu muc gia: dung bien moi truong khong co, nen thu truc tiep
    import importlib.util
    spec = importlib.util.spec_from_file_location("m", __file__)
    m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
    m.RES = os.path.join(d, "results")
    m.OUT = os.path.join(d, "results", "tables", "x.tex")
    try:
        sys.argv = ["x"]
        m.main()
        bat = False
    except SystemExit as e:
        bat = "KHONG tai lap duoc" in str(e)
    print("  %-52s %s" % ("ky nguyen dau khong khop Bang III: phai DUNG",
                          "DAT" if bat else "HONG"))
    ok = ok and bat
    print("\n  => %s" % ("TAT CA DAT" if ok else "CO CA HONG"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
